### ISSUE TITLE
Modelar Geografia.

### ISSUE THREAD

**Issue by bimconsultors** [ctrl-alt-d/proaV2#10]
Hauríem d'avançar en el tema de modelar Catalunya, Diputació, Consell Comarcal, Municipi. Amb dades oficials.

**Comment by ctrl-alt-d** [comment]
De: <[sad@idescat.cat](mailto:sad@idescat.cat)>
Date: dv., 5 de maig 2023 a les 14:54
Subject: Demanda d'informació estadística (D536/2023)
To: <[bimconsultors@bimconsultors.com](mailto:bimconsultors@bimconsultors.com)>


Benvolgut senyor,

En resposta a la vostra petició, us comuniquem que trobareu aquesta informació a l'apartat Mètodes > Classificacions i codis > Codis territorials i d'entitats > Municipis del nostre web, l'adreça concreta del qual és: https://www.idescat.cat/codis/?id=50&n=9. Us podeu baixar el llistat en format CSV prement el botó 'Descarregar', situat a la part superior de la pàgina.

El codi de la columna de l'esquerra us informa de la província a la qual pertany cada municipi:

08XXXX: Barcelona
17XXXX: Girona
25XXXX: Lleida
43XXXX: Tarragona

Esperem que aquesta informació us sigui d'utilitat i restem a la vostra disposició per a qualsevol altre dubte o aclariment.

Atentament,

Javier Nieto Arroyo
Biblioteca
Àrea de Comunicació
Subdirecció General d'Informació i Comunicació
Institut d'Estadística de Catalunya (Idescat)

**Comment by bimconsultors** [comment]
Pensant com fer el model, i manipulant les dades, no es pot assumir la relació Un municipi pertany a un consell comarcal, i un consell comarcal pertany a una província. Hi ha municipis del mateix consell comarcal que poden pertànyer a províncies diferents.
